import { ArrowDownward } from "@mui/icons-material";

export const data = {
  user: {
    name: "Noppadon Raksasiripong",
    tagline: "Full-Stack Javascript Developer(Reactjs,Nextjs,Nodejs,Express)",
    email: "noppadol.raksa@gmail.com",
    github: "https://github.com/noppadolraksa",
    website: "",
    strength: "Fast learner",
    englishSkill: "Intermediate",
    born: "January 8th 1995",
    objective: "",
    phone: "0875606096",
    frontEndSkills: [
      "Reactjs",
      "Nextjs",
      "Html",
      "Css",
      "Javascript",
      "Typescript",
      "Redux",
      "ContextApi",
      "Styled-component",
      "Tailwind",
      "Firebase",
    ],
    backEndSkills: [
      "NodeJs",
      "ExpressJs",
      "Graphql",
      "Mongodb",
      "SQL",
      "Prisma",
      "Authentication & Authorization*",
      "Redis",
      "Socket.io",
      "Web Security",
    ],
    infrastructures: ["Docker", "Heroku", "Github"],
    // project: [
    //   {
    //     title: "E-Commerce",
    //     description:
    //       "MERN Stack E-commerce from scratch for practice with 30 pages that user can add products to cart and buy it then the the bill will show in admin dashboard",
    //     technologies: [
    //       "ReactJS",
    //       "Redux",
    //       "Redux-persist",
    //       "Styled-components",
    //       "MUI",
    //       "React-hook-form",
    //       "Axios",
    //       "Firebase-Storage",
    //       "Stripe",
    //       "ExpressJS",
    //       "Dotenv",
    //       "Mongoose",
    //       "Cors",
    //       "Nodemon",
    //       "Jsonwebtoken",
    //       "CrtyptoJS",
    //       "Docker",
    //     ],
    //     techniques: [
    //       "Login/registration",
    //       "State management(redux)",
    //       "Authentication(JWT) & authorization(User or Admin)",
    //       "Responsive (mobile, tablet, PC)",
    //       "Form with error handling",
    //       "Data visualization(charts & tables)",
    //       "Payment(stripe)",
    //       "Dockerize",
    //       "Dashboard(monthly reports & user reports & order list)",
    //     ],
    //     sourceCode:
    //       "https://github.com/noppadolraksa/e-commerce,https://github.com/noppadolraksa/E-commerce-backend,https://github.com/noppadolraksa/e-commerce-admin",
    //     link1: "https://my-shop-e-commerce.netlify.app",
    //     link2: "https://my-shop-admin.netlify.app",
    //     link3: "https://prezi.com/p/e8h1eijgkuo1/?present=1",
    //   },
    //   {
    //     title: "Portfolio",
    //     description:
    //       "Nextjs with graghQL, Nexus, Apollo,Prisma, postgreSQL and typescript",
    //     technologies: [
    //       "NextJs",
    //       "Prisma",
    //       " Apollo",
    //       " Nexus",
    //       " GraphQL",
    //       " PostgreSQL",
    //       "Typescript",
    //       " Styled-component",
    //       "Next-themes",
    //     ],
    //     techniques: [
    //       "Dark-mode",
    //       "Seeding data",
    //       "Type-safe with Nexus schema",
    //       "Nested Comments(tree-like structure)",
    //     ],
    //     sourceCode: "https://github.com/noppadolraksa/portfolio",
    //   },
    //   {
    //     title: "Serverless chat app ",
    //     description: "Serverless Nextjs with firebase, tailwind and typescript",
    //     technologies: [
    //       "NextJs",
    //       "React-hook-form",
    //       " Firebase-authentucation",
    //       " Firestore",
    //       "Tailwind",
    //       " Antd",
    //     ],
    //     techniques: [
    //       "login-register with firebase authentication",
    //       "cool UI with antd and tailwind",
    //       "Update realtime chatapp,Form handling,",
    //     ],
    //     sourceCode: "https://github.com/noppadolraksa/nextchatapp",
    //   },
    // ],
    // education: [
    //   {
    //     degree: "High school",
    //     institution: "Wat Nuan Noradit School",
    //     date: "",
    //     fieldOfStudy: "Math&Science",
    //   },
    //   {
    //     degree: "Bachelor degree",
    //     institution: "Faculty of Economics Thammasat University",
    //     date: "",
    //     fieldOfStudy: "Major:Business, Minor:International Business",
    //   },
    //   {
    //     degree: "Codecamp",
    //     institution: "Freecodecamp",
    //     date: "",
    //     fieldOfStudy: "html,css,javascript,frontend,backend",
    //   },
    // ],
  },
  project: [
    {
      title: "E-Commerce",
      description:
        "MERN Stack E-commerce from scratch for practice with 30 pages that user can add products to cart and buy it then the the bill will show in admin dashboard",
      technologies: [
        "ReactJS",
        "Redux",
        "Redux-persist",
        "Styled-components",
        "MUI",
        "React-hook-form",
        "Axios",
        "Firebase-Storage",
        "Stripe",
        "ExpressJS",
        "Dotenv",
        "Mongoose",
        "Cors",
        "Nodemon",
        "Jsonwebtoken",
        "CrtyptoJS",
        "Docker",
      ],
      techniques: [
        "Login/registration",
        "State management(redux)",
        "Authentication(JWT) & authorization(User or Admin)",
        "Responsive (mobile, tablet, PC)",
        "Form with error handling",
        "Data visualization(charts & tables)",
        "Payment(stripe)",
        "Dockerize",
        "Dashboard(monthly reports & user reports & order list)",
      ],
      sourceCode:
        "https://github.com/noppadolraksa/e-commerce,https://github.com/noppadolraksa/E-commerce-backend,https://github.com/noppadolraksa/e-commerce-admin",
      link1: "https://my-shop-e-commerce.netlify.app",
      link2: "https://my-shop-admin.netlify.app",
      link3: "https://prezi.com/p/e8h1eijgkuo1/?present=1",
    },
    {
      title: "Portfolio",
      description:
        "Nextjs with graghQL, Nexus, Apollo,Prisma, postgreSQL and typescript",
      technologies: [
        "NextJs",
        "Prisma",
        " Apollo",
        " Nexus",
        " GraphQL",
        " PostgreSQL",
        "Typescript",
        " Styled-component",
        "Next-themes",
      ],
      techniques: [
        "Dark-mode",
        "Seeding data",
        "Type-safe with Nexus schema",
        "Nested Comments(tree-like structure)",
      ],
      sourceCode: "https://github.com/noppadolraksa/portfolio",
    },
    {
      title: "Serverless chat app ",
      description: "Serverless Nextjs with firebase, tailwind and typescript",
      technologies: [
        "NextJs",
        "React-hook-form",
        " Firebase-authentucation",
        " Firestore",
        "Tailwind",
        " Antd",
      ],
      techniques: [
        "login-register with firebase authentication",
        "cool UI with antd and tailwind",
        "Update realtime chatapp,Form handling,",
      ],
      sourceCode: "https://github.com/noppadolraksa/nextchatapp",
    },
  ],
  education: [
    {
      degree: "High school",
      institution: "Wat Nuan Noradit School",

      fieldOfStudy: "Math&Science",
    },
    {
      degree: "Bachelor degree",
      institution: "Faculty of Economics Thammasat University",

      fieldOfStudy: "Major:Business, Minor:International Business",
    },
    {
      degree: "Codecamp",
      institution: "Freecodecamp",

      fieldOfStudy: "html,css,javascript,frontend,backend",
    },
  ],
};
